### ISSUE TITLE
No module named 'torchbiggraph.converters.importers'

### ISSUE THREAD

**Issue by yoeHuuui** [pinellolab/simba#22]
simba is a very useful tool for single-cell data analysis! 
However, when I attempted to install simba using pip in Python 3.8.0, I encountered the following error:
```
>>> import simba as si
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/miniconda3/envs/simba/lib/python3.8/site-packages/simba/__init__.py", line 5, in <module>
    from . import tools as tl
  File "/home/miniconda3/envs/simba/lib/python3.8/site-packages/simba/tools/__init__.py", line 12, in <module>
    from ._pbg import (
  File "/home/miniconda3/envs/simba/lib/python3.8/site-packages/simba/tools/_pbg.py", line 14, in <module>
    from torchbiggraph.converters.importers import (
ModuleNotFoundError: No module named 'torchbiggraph.converters.importers'
```
It seems that this issue is related to torchbiggraph. My torchbiggraph version is ```v1.0.0```.
What is the version of torchbiggraph in simba, or how can I resolve this issue? 
Thank you very much!

**Comment by yoeHuuui** [comment]
I have solved the problem by using the following command:
```pip install git+https://github.com/pinellolab/simba_pbg```
Very nice tool!
